# Generated by Django 5.0.3 on 2024-03-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment_System_API', '0003_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'permissions': [('view_other_appointment', 'Can view other appointment')]},
        ),
    ]
